version: '2'
services:
  historial-db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_USER: juancho
      MYSQL_PASSWORD: asdf
      MYSQL_DATABASE: historial
      MYSQL_HOST: historial-db
  historial-ms:
    image: jcgamar/historial-bicirun:estable
    ports:
      - "3002:9001"
    depends_on:
      - historial-db